DEFAULT_FONT = ("Helvetica", 20)
ROW_OPTIONS = [str(i) for i in range(3, 12)]
CONNECT_OPTIONS = [str(i) for i in range(3, 9)]
DEFAULT_WIDGET_BG = "lightgreen"
DEFAULT_HIGHLIGHT_COLOR = "salmon"
DEFAULT_ACTIVE_COLOR = "navy"
DEFAULT_ENTRY_COLOR = "paleturquoise"
ENTRY_WIDTH = 10
NAME_LIMIT = 9
WAIT_TIME = 0.7